//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.AppData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ID { get; set; }
        public int ID_Question { get; set; }
        public string Text { get; set; }
        public bool Is_Correct { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
